// Escudos de los clubes (bucket "escudos" de Supabase).
// Copia de ESCUDOS_SUPABASE de la app (futboleros/screens/Figurita.js): si se agregan clubes allá, actualizar acá.
// Las entradas más específicas van primero para evitar conflictos ("independiente rivadavia" antes que "independiente").
const ESCUDOS: [string, string][] = [
  // Argentina — AFA Primera División
  ['river plate',              'river'],
  ['river',                    'river'],
  ['boca juniors',             'boca'],
  ['boca',                     'boca'],
  ['independiente rivadavia',  'independienteriv'],
  ['independiente',            'independiente'],
  ['racing club',              'racing'],
  ['racing cordoba',           'racing_cordoba'],
  ['racing santander',         'racingsantander'],
  ['san lorenzo',              'sanlorenzo'],
  ['huracan',                  'huracan'],
  ['velez',                    'velez'],
  ['estudiantes de la plata',  'estudianteslp'],
  ['estudiantes rio cuarto',   'estudiantesrc'],
  ['estudiantes',              'estudiantes'],
  ['gimnasia y tiro',          'gimnasia_y_tiro'],
  ['gimnasia jujuy',           'gimnasiajujuy'],
  ['gimnasia mendoza',         'gimnasiamendoza'],
  ['gimnasia',                 'gimnasia'],
  ['talleres',                 'talleres'],
  ['belgrano',                 'belgrano'],
  ['colon',                    'colon'],
  ["newell's",                 'newells'],
  ['newells',                  'newells'],
  ['rosario central',          'rosariocentral'],
  ['central cordoba',          'centralcordoba'],
  ['lanus',                    'lanus'],
  ['banfield',                 'banfield'],
  ['platense',                 'platense'],
  ['aldosivi',                 'aldosivi'],
  ['tigre',                    'tigre'],
  ['argentinos juniors',       'argentinos'],
  ['argentinos',               'argentinos'],
  ['arsenal de sarandi',       'arsenalsarandi'],
  ['arsenal sarandi',          'arsenalsarandi'],
  ['riestra',                  'riestra'],
  ['godoy cruz',               'godoycruz'],
  ['sarmiento',                'sarmiento'],
  ['atletico tucuman',         'atleticotucuman'],
  ['tucuman',                  'atleticotucuman'],
  ['atletico rafaela',         'atleticorafaela'],
  ['patronato',                'patronato'],
  ['union santa fe',           'union'],
  ['union',                    'union'],
  ['barracas central',         'barracas'],
  ['barracas',                 'barracas'],
  ['instituto',                'instituto'],
  ['defensa y justicia',       'defensa'],
  ['defensa',                  'defensa'],
  ['san martin san juan',      'sanmartinsj'],
  ['san martin tucuman',       'sanmartintuc'],
  ['san martin',               'sanmartinsj'],
  // Argentina — Nacional B y otros
  ['almirante brown',          'almirante'],
  ['all boys',                 'allboys'],
  ['almagro',                  'almagro'],
  ['agropecuario',             'agropecuario'],
  ['acassuso',                 'acassuso'],
  ['armenio',                  'armenio'],
  ['atlanta',                  'atlanta'],
  ['berazategui',              'berazategui'],
  ['brown adrogue',            'brownadrogue'],
  ['canuelas',                 'canuelas'],
  ['central ballester',        'centralballester'],
  ['central espanol',          'central_espanol'],
  ['central norte',            'central_norte'],
  ['chacarita',                'chacarita'],
  ['chaco for ever',           'chaco_for_ever'],
  ['ciudad bolivar',           'ciudad_bolivar'],
  ['claypole',                 'claypole'],
  ['colegiales',               'colegiales'],
  ['comunicaciones',           'comunicaciones'],
  ['defensores',               'defensores'],
  ['deportivo espanol',        'depespanol'],
  ['deportivo madryn',         'deportivo_madryn'],
  ['deportivo merlo',          'depmerlo'],
  ['dock sud',                 'dock_sud'],
  ['el porvenir',              'elporvenir'],
  ['estrella del sur',         'estrella_del_sur'],
  ['excursionistas',           'excursionistas'],
  ['ferrocarril oeste',        'ferro'],
  ['ferro',                    'ferro'],
  ['flandria',                 'flandria'],
  ['guemes',                   'guemes'],
  ['juventud unida',           'juventudunida'],
  ['laferrere',                'laferrere'],
  ['leones',                   'leones'],
  ['liniers',                  'liniers'],
  ['los andes',                'losandes'],
  ['lujan',                    'lujan'],
  ['lugano',                   'lugano'],
  ['midland',                  'midland'],
  ['mitre',                    'mitre'],
  ['moron',                    'moron'],
  ['muniz',                    'muniz'],
  ['nueva chicago',            'nueva_chicago'],
  ['puerto nuevo',             'puertonuevo'],
  ['quilmes atletico',         'argquilmes'],
  ['quilmes',                  'quilmes'],
  ['real pilar',               'realpilar'],
  ['recoleta fc',              'recoleta_fc'],
  ['sacachispas',              'sacachispas'],
  ['san miguel',               'sanmiguel'],
  ['san telmo',                'santelmo'],
  ['sm burzaco',               'smburzaco'],
  ['sportivo barrancas',       'sportivoBarracas'],
  ['sportivo italiano',        'spitaliano'],
  ['temperley',                'temperley'],
  ['tristan suarez',           'tristansuarez'],
  ['uai urquiza',              'uaiurquiza'],
  ['victoriano',               'victoriano'],
  ['villa calmine',            'villacalmine'],
  ['villa san carlos',         'villasancarlos'],
  ['yupanqui',                 'yupanqui'],
  ['2 de mayo',                '2demayo'],
  // Brasil
  ['atletico mineiro',         'atlmineiro'],
  ['atletico paranaense',      'atlparanaense'],
  ['bahia',                    'bahia'],
  ['botafogo',                 'botafogo'],
  ['bragantino',               'rbbragantino'],
  ['chapecoense',              'chapecoense'],
  ['corinthians',              'corinthians'],
  ['coritiba',                 'coritiba'],
  ['cruzeiro',                 'cruzeiro'],
  ['flamengo',                 'flamengo'],
  ['fluminense',               'fluminense'],
  ['gremio',                   'gremio'],
  ['internacional',            'internacional'],
  ['palmeiras',                'palmeiras'],
  ['rb bragantino',            'rbbragantino'],
  ['remo',                     'remo'],
  ['santos',                   'santos'],
  ['sao paulo',                'saopaulo'],
  ['vasco',                    'vasco'],
  ['vitoria',                  'vitoria'],
  // Uruguay
  ['boston river',             'bostonriver'],
  ['cerro largo',              'cerrolargo'],
  ['cerro porteno',            'cerroporteno'],
  ['cerro',                    'cerro'],
  ['danubio',                  'danubio'],
  ['defensor sporting',        'defensor'],
  ['fenix',                    'fenix'],
  ['juventud',                 'juventud'],
  ['libertad',                 'libertad'],
  ['maldonado',                'maldonado'],
  ['montevideo city',          'montevideocity'],
  ['nacional',                 'nacional'],
  ['olimpia',                  'olimpia'],
  ['penarol',                  'penarol'],
  ['progreso',                 'progreso'],
  ['wanderers',                'wanderers'],
  // Paraguay
  ['atletico tembetary',       'atletico_tembetary'],
  ['deportivo paraguayo',      'depparaguayo'],
  ['general caballero',        'general_caballero'],
  ['guarani',                  'guarani'],
  ['olimpia',                  'olimpia'],
  ['sportivo ameliano',        'sportivo_ameliano'],
  ['sportivo luqueno',         'sportivoluqueno'],
  ['sportivo trinidense',      'sportivo_trinidense'],
  // Chile
  ['audax italiano',           'audax'],
  ['cobresal',                 'cobresal'],
  ['colo-colo',                'colocolo'],
  ['colo colo',                'colocolo'],
  ['coquimbo unido',           'coquimbo'],
  ['deportes concepcion',      'deportes_concepcion'],
  ['deportes la serena',       'deplaserena'],
  ['deportes limache',         'deportes_limache'],
  ['everton',                  'evertonin'],
  ['huachipato',               'huachipato'],
  ['nublense',                 'nublense'],
  ['ohiggins',                 'ohiggins'],
  ["o'higgins",                'ohiggins'],
  ['palestino',                'palestino'],
  ['u de chile',               'udechile'],
  ['universidad de chile',     'udechile'],
  ['universidad de concepcion','udeconcepcion'],
  ['universidad catolica',     'ucatolica'],
  ['union la calera',          'unionlacalera'],
  // España
  ['alaves',                   'alaves'],
  ['athletic bilbao',          'athletic'],
  ['atletico madrid',          'atlmadrid'],
  ['barcelona',                'barcelona'],
  ['betis',                    'betis'],
  ['celta',                    'celta'],
  ['deportivo coruna',         'deportivocoruna'],
  ['deportivo la coruna',      'deportivocoruna'],
  ['elche',                    'elche'],
  ['espanyol',                 'espanyol'],
  ['espanyol barcelona',       'espanyol'],
  ['getafe',                   'getafe'],
  ['levante',                  'levante'],
  ['malaga',                   'malaga'],
  ['osasuna',                  'osasuna'],
  ['rayo vallecano',           'rayovallecano'],
  ['real madrid',              'realmadrid'],
  ['real sociedad',            'realsociedad'],
  ['sevilla',                  'sevilla'],
  ['valencia',                 'valencia'],
  ['villarreal',               'villarreal'],
  // Inglaterra
  ['arsenal',                  'arsenal'],
  ['aston villa',              'astonvilla'],
  ['bournemouth',              'bournemouth'],
  ['brentford',                'brentford'],
  ['brighton',                 'brighton'],
  ['chelsea',                  'chelsea'],
  ['coventry',                 'coventry'],
  ['crystal palace',           'crystalpalace'],
  ['everton',                  'everton'],
  ['fulham',                   'fulham'],
  ['hull city',                'hull_city'],
  ['ipswich',                  'ipswich_town'],
  ['leeds',                    'leeds'],
  ['liverpool',                'liverpool'],
  ['manchester city',          'manchestercity'],
  ['manchester united',        'manchesterunited'],
  ['newcastle',                'newcastle'],
  ['nottingham forest',        'nottingham_forest'],
  ['sunderland',               'sunderland'],
  ['tottenham',                'tottenham'],
  // Alemania
  ['augsburg',                 'augsburgo'],
  ['bayer leverkusen',         'bayerleverkusen'],
  ['bayern',                   'bayernmuenchen'],
  ['borussia dortmund',        'borussiadortmund'],
  ['borussia monchengladbach', 'bmonchengladbach'],
  ['eintracht frankfurt',      'eintrachtfrankfurt'],
  ['friburgo',                 'friburgo'],
  ['freiburg',                 'friburgo'],
  ['hamburgo',                 'hamburgo'],
  ['hamburger sv',             'hamburgo'],
  ['hoffenheim',               'hoffenheim'],
  ['koln',                     'koln'],
  ['mainz',                    'mainz05'],
  ['paderborn',                'paderborn07'],
  ['rb leipzig',               'rbleipzig'],
  ['schalke',                  'schalke04'],
  ['stuttgart',                'stuttgart'],
  ['union berlin',             'unionberlin'],
  ['werder bremen',            'werderbremen'],
  // Países Bajos
  ['ajax',                     'ajax'],
  ['az alkmaar',               'az'],
  ['excelsior',                'excelsior'],
  ['feyenoord',                'feyenoord'],
  ['fortuna sittard',          'fortunasittard'],
  ['go ahead eagles',          'go_ahead_eagles'],
  ['groningen',                'groningen'],
  ['heracles',                 'heracles'],
  ['nac breda',                'nac_breda'],
  ['nec nijmegen',             'nec'],
  ['psv',                      'psv'],
  ['sc heerenveen',            'scheerenveen'],
  ['sparta rotterdam',         'sparta'],
  ['telstar',                  'telstar'],
  ['twente',                   'twente'],
  ['utrecht',                  'utrecht'],
  ['volendam',                 'volendam'],
  ['zwolle',                   'zwolle'],
  // Otros Europa
  ['elversberg',               'elversberg'],
  ['inter miami',              'intermiami'],
]

const norm = (s: string) => s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase()

export function urlEscudo(club: string) {
  const lc = norm(club)
  for (const [keyword, archivo] of ESCUDOS) {
    if (lc.includes(norm(keyword))) return `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/escudos/${archivo}.png`
  }
  return null
}
